.travis.yml
lib/resources/PhoneNumbers.js
lib/resources/PhoneNumbersMessaging.js
lib/resources/PhoneNumbersVoice.js
lib/telnyx.js
test/resources/MessagingPhoneNumbers.spec.js
test/resources/PhoneNumbers.spec.js
test/resources/PhoneNumbersMessaging.spec.js
test/resources/PhoneNumbersVoice.spec.js

[PORTAL-611](https://telnyx.atlassian.net/browse/PORTAL-611)
Reference: https://developersdev.telnyx.com/docs/api/v2/numbers/Phone-Numbers
This depends on updating [Telnyx Mock](https://github.com/team-telnyx/telnyx-mock)

feat(resources): Phone Numbers Resource

---

lib/resources/Actions.js
lib/resources/ActionsSimCards.js
lib/resources/SimCards.js
lib/telnyx.js
test/resources/ActionsSimCards.spec.js
test/resources/SimCards.spec.js

[PORTAL-610](https://telnyx.atlassian.net/browse/PORTAL-610)
Reference: https://developers.telnyx.com/docs/api/v2/wireless/SIM-Cards
This depends on updating [Telnyx Mock](https://github.com/team-telnyx/telnyx-mock)

feat(resources): SIM Cards Resource

---

.travis.yml
lib/resources/BillingGroups.js
lib/telnyx.js
test/resources/BillingGroups.spec.js

[PORTAL-770](https://telnyx.atlassian.net/browse/PORTAL-770)
Reference: https://developers.telnyx.com/docs/api/v2/billing-groups/Billing-Groups

feat(resources): Billing Groups

---

lib/resources/IpConnections.js
lib/telnyx.js
test/resources/IpConnections.spec.js

[PORTAL-771](https://telnyx.atlassian.net/browse/PORTAL-771)
Reference: https://developers.telnyx.com/docs/api/v2/connections/IP-Connections

feat(resources): IP Connections

---

lib/resources/FqdnConnections.js
lib/telnyx.js
test/resources/FqdnConnections.spec.js

[PORTAL-772](https://telnyx.atlassian.net/browse/PORTAL-772)
Reference: https://developersdev.telnyx.com/docs/api/v2/connections/FQDN-Connections

feat(resources): FQDN Connections

---

lib/resources/CredentialConnections.js
lib/telnyx.js
test/resources/CredentialConnections.spec.js

[PORTAL-772](https://telnyx.atlassian.net/browse/PORTAL-772)
Reference: https://developersdev.telnyx.com/docs/api/v2/connections/FQDN-Connections

feat(resources): Credential Connections

---

.travis.yml
lib/resources/NumberOrderDocuments.js
lib/resources/PhoneNumberRegulatoryRequirements.js
lib/resources/RegulatoryRequirements.js
lib/telnyx.js
test/resources/NumberOrderDocuments.spec.js
test/resources/PhoneNumbersRegulatoryRequirements.spec.js
test/resources/RegulatoryRequirements.spec.js

[PORTAL-791](https://telnyx.atlassian.net/browse/PORTAL-791)
Reference: 
- https://developers.telnyx.com/docs/api/v2/numbers/Number-Order-Regulatory-Requirements
- https://developers.telnyx.com/docs/api/v2/numbers/Number-Order-Documents
**update:** This depends on https://github.com/team-telnyx/telnyx-mock/pull/12 to pass tests

feat(resources): Number Order Regulatory Requirements and Number Order Documents

---

.travis.yml
package.json
test/resources/AvailablePhoneNumbers.spec.js
test/resources/Messages.spec.js
test/resources/MessagingProfiles.spec.js
test/resources/MessagingShortCodes.spec.js
test/resources/NumberReservations.spec.js
test/resources/PhoneNumbersRegulatoryRequirements.spec.js
test/resources/RegulatoryRequirements.spec.js

this depends on having a new version of [telnyx-mock](https://github.com/team-telnyx/telnyx-mock) containing the https://github.com/team-telnyx/telnyx-mock/pull/13 updates in order to pass tests

update specs according to Numbers Specs Update (Telnyx Mock v0.7.3)

---

lib/resources/Connections.js
lib/telnyx.js
test/resources/ActionsSimCards.spec.js
test/resources/BillingGroups.spec.js
test/resources/Conferences.spec.js
test/resources/Connections.spec.js
test/resources/CredentialConnections.spec.js
test/resources/FqdnConnections.spec.js
test/resources/Fqdns.spec.js
test/resources/IpConnections.spec.js
test/resources/Ips.spec.js
test/resources/Messages.spec.js
test/resources/MessagesSenderIds.spec.js
test/resources/MessagingPhoneNumbers.spec.js
test/resources/MessagingSenderIds.spec.js
test/resources/MessagingShortCodes.spec.js
test/resources/NumberOrderDocuments.spec.js
test/resources/NumberOrders.spec.js
test/resources/NumberReservations.spec.js
test/resources/PhoneNumbers.spec.js
test/resources/PhoneNumbersMessaging.spec.js
test/resources/PhoneNumbersRegulatoryRequirements.spec.js
test/resources/PhoneNumbersVoice.spec.js
test/resources/RegulatoryRequirements.spec.js
testUtils/index.js

This PR depends on [Telnyx Mock new Release 0.8.0](https://github.com/team-telnyx/telnyx-mock/pull/16) for specs to pass.

feat(resources): add Connections Resource

---

.travis.yml
lib/resources/MessagingProfiles.js
lib/resources/MessagingSenderIds.js
test/resources/Conferences.spec.js
test/resources/MessagesSenderIds.spec.js
test/resources/MessagingProfiles.spec.js
test/resources/MessagingSenderIds.spec.js
test/resources/NumberReservations.spec.js
test/resources/PhoneNumbersRegulatoryRequirements.spec.js
test/resources/PublicKey.spec.js
test/resources/SimCards.spec.js

all outdated tests from 0.8.0 updated to 0.8.8 mock tests

Fixed outdated tests

---

.travis.yml
lib/resources/MessagingProfiles.js
lib/resources/MessagingSenderIds.js
lib/resources/Outbound.js
lib/telnyx.js
test/resources/Conferences.spec.js
test/resources/MessagesSenderIds.spec.js
test/resources/MessagingProfiles.spec.js
test/resources/MessagingSenderIds.spec.js
test/resources/NumberReservations.spec.js
test/resources/Outbound.spec.js
test/resources/PhoneNumbersRegulatoryRequirements.spec.js
test/resources/PublicKey.spec.js
test/resources/SimCards.spec.js

[PORTAL-936](https://telnyx.atlassian.net/secure/RapidBoard.jspa?rapidView=92&modal=detail&selectedIssue=PORTAL-936&assignee=5e679d5b77d46c0cf93af075)
Outbound voice profiles endpoint

Feat(portal 936) outbound voice profiles endpoint

---

lib/resources/ActionsSimCards.js
lib/resources/SimCards.js
test/resources/ActionsSimCards.spec.js
test/resources/SimCards.spec.js

https://developersdev.telnyx.com/docs/api/v2/wireless/SIM-Cards

feat(resources): SIM Card Network Preferences

---

lib/resources/MobileOperatorNetworks.js
lib/telnyx.js
test/resources/MobileOperatorNetworks.spec.js

https://developers.telnyx.com/docs/api/v2/wireless/Mobile-Operator-Networks

feat(resources): Mobile Operator Networks

---

lib/resources/SimCardGroups.js
lib/telnyx.js
test/resources/MobileOperatorNetworks.spec.js
test/resources/SimCardGroups.spec.js

https://developers.telnyx.com/docs/api/v2/wireless/SIM-Card-Groups
**blockings**: This PR depends on updating the SIM Card Groups specs to include the `data` wrapper here https://github.com/team-telnyx/openapi-internal/pull/223

feat(resources): SIM Card Groups Resource

---

lib/resources/NumberLookup.js
lib/telnyx.js
test/resources/NumberLookup.spec.js

https://developers.telnyx.com/docs/api/v2/number-lookup/Number-Lookup

feat(resources): Number Lookup

---

lib/resources/Balance.js
lib/telnyx.js
test/resources/Balance.spec.js

https://developers.telnyx.com/docs/api/v2/account/Billing

feat(resources): Balance

---

lib/resources/Addresses.js
lib/telnyx.js
test/resources/Addresses.spec.js

https://developers.telnyx.com/docs/api/v2/account/Addresses

feat(resources): Addresses

---

lib/resources/Faxes.js
lib/telnyx.js
test/resources/Faxes.spec.js

https://developers.telnyx.com/docs/api/v2/programmable-fax/Programmable-Fax-Commands

feat(resources): Faxes

---

lib/resources/SimCards.js
test/resources/NumberReservations.spec.js
test/resources/PhoneNumberInboundChannels.spec.js
test/resources/SimCards.spec.js

https://developersdev.telnyx.com/docs/api/v2/wireless/SIM-Cards#SimCardEnable
https://developersdev.telnyx.com/docs/api/v2/wireless/SIM-Cards#SimCardDisable

feat(resources): Sim Card Enable/Disable

---

lib/resources/MessagingProfileMetrics.js
lib/resources/MessagingProfiles.js
lib/resources/ShortCodes.js
lib/telnyx.js
test/resources/MessagingProfileMetrics.spec.js
test/resources/MessagingProfiles.spec.js
test/resources/OtaUpdates.spec.js
test/resources/ShortCodes.spec.js

https://developers.telnyx.com/docs/api/v2/messaging/Messaging-Profiles
https://developers.telnyx.com/docs/api/v2/messaging/Short-Codes

feat(resources): Messaging Profile Metrics and Short Codes

---

test/resources/Calls.spec.js
test/resources/Messages.spec.js
test/resources/MessagingPhoneNumbers.spec.js
test/resources/MessagingProfiles.spec.js

Docs were updated as well as `telnyx-mock`. This PR updates specs to match

Update Calls and Messaging Specs

---

lib/resources/PhoneNumbers.js
test/resources/PhoneNumbers.spec.js

fix(resources): Add support to Phone Numbers Retrieve method

---

.github/workflows/node.js.yml
.github/workflows/npm-publish.yml

Publish to NPM on release mint

Auto NPM publish

---

lib/resources/AccessTokens.js
lib/resources/Rooms.js
lib/telnyx.js
test/resources/AccessTokens.spec.js
test/resources/Rooms.spec.js

Currently in `v2-beta`, only work in development environments. Skipping tests as API documentation is not yet written and `telnyx-mock` doesn't mock them.

[VIDEO-55] Add Access Tokens and Rooms resources

---

lib/resources/AccessTokens.js
test/resources/AccessTokens.spec.js

Adds support for the first grant an Access Token can have: Video Rooms.

[VIDEO-56] Access Token grants

---

test/resources/TelephonyCredentials.spec.js
test/resources/Verifications.spec.js
test/resources/VerificationsByPhoneNumber.spec.js
test/resources/VerifyProfiles.spec.js

update master branch for alignment with telnyx-mock

skipped verify specs (forthcoming updates), fixed tc spec

---

lib/resources/Calls.js
lib/resources/Queues.js
lib/telnyx.js
test/resources/Calls.spec.js
test/resources/Queues.spec.js

https://telnyx.atlassian.net/browse/DEVEX-405

Queue commands

---

lib/resources/Conferences.js
test/resources/Conferences.spec.js

* retrieve conference
* list participants
* speak
* play audio
* stop audio
* record_start
* record_stop
* update participant
* leave conference

additional support for conference calls

---

.github/scripts/before_install.sh
README.md

Update location of telnyx-prism-mock service

Telnyx Prism Mock

---

README.md

Simply fixing a README Typo, Cheers !

FIX: README Typo
